### PR TITLE
Sockets attempt

### PR DESCRIPTION
**Pull request by ckvuby**
Send msg from frontend
save in backend model in messages class
render on frontend messages from backend

### CODE REVIEW

**Comment by ckvuby** [comment]
[Implement websockets in frontend and backend and make backend websocket console.log what's send from frontend](https://trello.com/c/y85kfeb2/52-implement-websockets-in-frontend-and-backend-and-make-backend-websocket-consolelog-whats-send-from-frontend)

**Comment by TinyGobby** [comment]
[Implement socket.io in frontend and backend](https://trello.com/c/eo4QRJSN/60-implement-websockets-in-frontend-and-backend)

**Comment by TinyGobby** [comment]
[Using socket.io to pass information](https://trello.com/c/hpM8zirL/63-using-socketio-to-pass-information)

**Comment by TinyGobby** [comment]
[Message model on backend](https://trello.com/c/abZpNKwu/71-message-model-on-backend)

**Comment by TinyGobby** [comment]
[Messages on the backend is rendered on the frontend](https://trello.com/c/KK49Y6bK/72-messages-on-the-backend-is-rendered-on-the-frontend)

**Pull request merged**
