### PR TITLE
Update users on signup

### PR DESCRIPTION
**Pull request by sebgrebe**
- When signing up, everyone's user list is updated via socket
- When starting a game, everyone's user list is revealed

### CODE REVIEW

**Comment by IvyMic** [comment]
[Update user list for all clients on signup of new user](https://trello.com/c/NJszKCgE/120-update-user-list-for-all-clients-on-signup-of-new-user)

**Comment by TinyGobby** [comment]
[Showing number of users before game started](https://trello.com/c/PzIiOxdo/113-showing-number-of-users-before-game-started)

**Comment by sebgrebe** [comment]
[Clear messages when all participants have left](https://trello.com/c/GQbhfawG/103-clear-messages-when-all-participants-have-left)

**Comment by sebgrebe** [comment]
[Update user list for all clients on signup of new user](https://trello.com/c/NJszKCgE/120-update-user-list-for-all-clients-on-signup-of-new-user)

**Pull request merged**
